<?php
require_once __DIR__ . '/auth.php';
function page_start(string $title, bool $admin = false): void { $me = user(); ?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?= e($title) ?> · iRent</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/style.css"></head><body>
<div class="ambient ambient-one"></div><div class="ambient ambient-two"></div>
<?php if ($admin): ?><aside class="sidebar"><a class="brand" href="dashboard_admin.php"><i>◉</i> iRent <span>ADMIN</span></a><nav>
<a href="dashboard_admin.php" class="<?= basename($_SERVER['PHP_SELF'])==='dashboard_admin.php'?'active':'' ?>">▦ Dashboard</a><a href="models.php" class="<?= basename($_SERVER['PHP_SELF'])==='models.php'?'active':'' ?>">◇ Model iPhone</a><a href="units.php" class="<?= basename($_SERVER['PHP_SELF'])==='units.php'?'active':'' ?>">▣ Unit Fisik</a><a href="rentals.php" class="<?= basename($_SERVER['PHP_SELF'])==='rentals.php'?'active':'' ?>">↗ Transaksi Sewa</a></nav><div class="sidebar-user"><small>Masuk sebagai</small><strong><?= e($me['username']) ?></strong><a href="logout.php">Keluar ↗</a></div></aside><main class="admin-main"><header class="topbar"><button class="menu-toggle" onclick="document.querySelector('.sidebar').classList.toggle('open')">☰</button><div><p class="eyebrow">CONTROL CENTER</p><h1><?= e($title) ?></h1></div><div class="avatar"><?= strtoupper(substr($me['username'],0,1)) ?></div></header>
<?php else: ?><header class="glass-header"><a class="brand" href="catalog.php"><i>◉</i> iRent</a><button class="menu-toggle" onclick="document.querySelector('.user-nav').classList.toggle('open')">☰</button><nav class="user-nav"><a href="catalog.php" class="<?= basename($_SERVER['PHP_SELF'])==='catalog.php'?'active':'' ?>">Katalog</a><?php if ($me): ?><a href="my_rentals.php" class="<?= basename($_SERVER['PHP_SELF'])==='my_rentals.php'?'active':'' ?>">Riwayat Saya</a><a href="profile.php" class="<?= basename($_SERVER['PHP_SELF'])==='profile.php'?'active':'' ?>">Profil Saya</a><span class="nav-user"><?= e($me['username']) ?></span><a class="outline-btn" href="logout.php">Keluar</a><?php else: ?><a href="login.php">Masuk</a><a class="primary-btn compact" href="register.php">Daftar</a><?php endif ?></nav></header><main class="user-main">
<?php endif; if ($message=flash('success')): ?><div class="alert success">✓ <?= e($message) ?></div><?php endif; if ($message=flash('error')): ?><div class="alert error">! <?= e($message) ?></div><?php endif; ?>
<?php }
function page_end(): void { ?></main><script src="assets/js/app.js"></script></body></html><?php }
